### 출처: Java의 정석 (기초편)

# 예외처리(Exception handling)

- ### try-catch문 사용하기
- ### 예외 선언하기(자기를 호출한 코드에 떠넘기기)
- ### 덮기(catch 블럭내에 아무것도 안쓴다.)

## 예외 클래스의 계층 구조

- Throwable	
  - Exception
    - ...
    - RuntimeException
      - ...
  - Error
    - ...

- RuntimeException 클래스와 그 자손들: 프로그래머의 실수로 발생하는 예외
  - 사용자의 실수와 같은 외적인 요인에 의해 발생하는 예외

- Exception 클래스와 그 자손들: 사용자의 실수와 같은 외적 요인에 의해 발생하는 예외
  - 프로그래머의 실수로 발생하는 예외

## 에러(Error)

프로그램 코드에 의해서 수습될 수 없는 심각한 오류

- 컴파일 에러
  - 컴파일 시에 발생하는 에러
- 런타임 에러
  - 실행 시에 발생하는 에러
- 논리적 에러
  - 실행은 되지만, 의도와 다르게 동작하는 것

## 예외(Exception)

프로그램 코드에 의해서 수습될 수 있는 다소 미약한 오류

### 예외처리 방식

try-catch문을 사용할때 발생한 예외의 종류와 일치하는 **단 한 개의 catch블럭만 수행하게 된다. (괄호 생략 불가)** 예외가 발생하면, 해당하는 클래스의 인스턴스가 생성된다.

### checked예외

컴파일러가 예외처리 여부를 체크한다.(예외처리 필수)
Exception클래스와 그 자손들이 해당

### unchecked예외

컴파일러가 예외처리 여부를 체크안한다.(예외처리 선택)
RuntimeException클래스와 그 자손들이 해당

### printStackTrace()

- 예외발생 당시의 호출스택에 있었던 메서드의 정보와 예외 메세지를 화면에 출력.

### getMessage()

- 발생한 예외클래스의 인스턴스에 저장된 메세지를 얻을 수 있다.

## 멀티 catch블럭

```java
try {
    ...
} catch (ExceptionA e) {
    e.printStackTrace();
} catch (ExceptionB e) {
    e.printStackTrace();
}
```
catch블럭을 '|'기호를 이용해 하나의 catch블럭으로 합칠 수 있다.(중복 제거)
```java
try {
    ...
} catch (ExceptionA | ExceptionB e) {
            e.printStackTrace();
}
```

## finally 블럭

예외의 발생여부에 상관없이 실행되어야할 코드를 포함.

```java
try {
  ...
} catch (Exception e) {
  ...
} finally {
  ...     // 여기 내용들이 실행되어야할 코드
}
```

## 예외 발생시키기

- 연산자 new를 이용해 예외 클래스 객체 생성
```java
Exception e = new Exception("고의로 예외 발생시킴");
```
- 키워드 throw를 이용해서 예외 발생
```java
throw e;
```
**객체만 생성해서는 예외를 발생시킬수 없다. 반드시 throw를 써줘야 한다.**

## 사용자 정의 예외

- 우리가 직접 예외 클래스를 정의할수 있다.
- 조상은 `Exception`과 `RuntimeException`중 선택

## 예외 되던지기

- 예외를 처리한 후 다시 예외를 발생시키는 것
- 호출한 메서드와 호출된 메서드 양쪽 모두에서 예외처리를 하는 것

```java
class Example {
  public static void main(String[] args) {
    try {
      method1();
    } catch (Exception e) {
      System.out.println("main메서드에서 예외처리");
    }
  }
  
  static void method1() throws Exception {
    try {
      throw new Exception();
    } catch (Exception e) {
      System.out.println("method1메서드에서 예외처리");
      throw e;      // 다시 예외를 발생시킴.
    }
  }
}
```
